version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=meetsync
      - POSTGRES_PASSWORD=meetsyncpass
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
  rails:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
